### ISSUE TITLE
Feature Request: searchEngineJumpCE 脚本版本号遵从《语义化版本控制规范 2.0.0》

### ISSUE THREAD

**Issue by Firef0x** [ywzhaiqi/userscript#39]
Y大 @ywzhaiqi ，您好！ :rose:

最近我在修改 `searchEngineJumpCE` 脚本时，遇到了一些错误。具体是我在执行 `npm install` 安装该脚本依赖时， `npm` 输出以下错误：

```sh
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid version: "4.2.1.4"
npm ERR!     at Object.module.exports.fixVersionField (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:183:13)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:30:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:29:15)

npm ERR!     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:342:33)
npm ERR!     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:126:33)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:266:40
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
```

通过搜索发现， GitHub 上还有两个类似的错误报告： 

- [Error: invalid version 1.0.0-pre+001 (preRelease and buildMetaData combination) · Issue #3671](https://github.com/npm/npm/issues/3671)
- [Grunt requires 3 fields in project version number · Issue #835](https://github.com/gruntjs/grunt/issues/835)

两者都指向一个问题：版本号没有遵从[《语义化版本控制规范 2.0.0》](http://semver.org/lang/zh-CN/)。

我在将 https://github.com/ywzhaiqi/userscript/blob/master/searchEngineJumpCE/package.json#L3 修改为

```javascript
 "version": "4.2.1",
```

后，再次执行 `npm install` 则正常运行。

虽然这不算一个大问题，还是恳求 Y 大能够遵从《语义化版本控制规范 2.0.0》，修改 `searchEngineJumpCE` 脚本的版本号。

此致！ :bow:

**Comment by ywzhaiqi** [comment]
此脚本我目前已经不用了，你自己改吧，目测这个脚本不再更新。

**Comment by Firef0x** [comment]
好吧，感谢回复！T^T :sob: :cry: 

祝您元宵节快乐！ :izakaya_lantern:
